import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://enterprise-e8038.firebaseapp.com/__/auth/action?apiKey=AIzaSyD9w7OjQ1mbRxWX-kqUelVtwpnrxAhkpaA&mode=signIn&oobCode=aqidqL8oCjes68MxSPJOwixQSOlrCMBRBzbcZnCnpm0AAAGNyhQK_w&continueUrl=https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/auth/passwordless?email%3Dnewtestingntake@gmail.com&lang=en');
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/auth/passwordless?email=newtestingntake@gmail.com&apiKey=AIzaSyD9w7OjQ1mbRxWX-kqUelVtwpnrxAhkpaA&oobCode=aqidqL8oCjes68MxSPJOwixQSOlrCMBRBzbcZnCnpm0AAAGNyhQK_w&mode=signIn&lang=en');
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/appointments');

  await page.locator('div').filter({ hasText: /^Settings$/ }).getByRole('img').click();
  await page.getByText('Team members').first().click();
  await page.getByRole('button', { name: 'Invite team member' }).nth(1).click();
  await page.getByLabel('Enter email').click();
  await page.getByLabel('Enter email').fill('testdemoramu@gmail.com');
  await page.getByLabel('Role').click();
  await page.getByRole('option', { name: 'Supervisor' }).click();
  await page.getByRole('button', { name: 'Send Invite' }).nth(1).click();
  await page.getByRole('button', { name: 'Done' }).nth(1).click();
// Calender Flows
  await page.getByText('Calendar').nth(1).click();
  await page.getByLabel('Monday').check();
  await page.locator('#root div').filter({ hasText: 'ReferralsCalendarClientsDocumentsReportsSettingsCalendarAvailabilityCurrently' }).getByRole('button').first().click();
  //uplaod Zip file
  await page.locator('div').filter({ hasText: /^Settings$/ }).getByRole('img').click();
  await page.getByText('Simple practice import').click();
  await page.getByRole('button', { name: 'Upload zip folder' }).nth(1).click();
  await page.getByTestId('ArrowBackRoundedIcon').locator('path').click();
  //Appoinment reports
  await page.locator('div').filter({ hasText: /^Reports$/ }).getByRole('img').click();
  await page.getByText('Appointment Notes').click();
  await page.locator('.btn-outline-default').first().click();
  await page.getByRole('tab', { name: 'Personal' }).click();
  await page.getByText('Progress notes').click();
  //After completeing the Appoinments notes back button
  await page.locator('div').filter({ hasText: /^Settings$/ }).getByRole('img').click();

  // Forms intake packets
  await page.locator('div').filter({ hasText: /^Documents$/ }).getByRole('img').click();
  await page.getByRole('button', { name: 'My intake packet' }).nth(1).click();
  await page.getByRole('button', { name: 'Add new' }).nth(1).click();
  await page.getByRole('tab', { name: 'My Forms' }).click();
  await page.getByLabel('Select forms').click();
  await page.getByRole('combobox', { name: 'Select forms' }).fill('Automa');
  await page.locator('[id="\\:rn\\:-option-0"]').first().click();
  await page.getByRole('combobox', { name: 'Select forms' }).click();
  await page.getByRole('button', { name: 'Add' }).nth(1).click();
  await page.locator('div').filter({ hasText: 'Forms added to intake package' }).nth(1).click();
  await page.locator('div').filter({ hasText: 'Forms added to intake package' }).nth(1).click();
  await page.locator('div').filter({ hasText: 'Forms added to intake package' }).nth(1).click();
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/verify?redirect_url=/forms/intake-package');
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/forms/intake-package');
  await page.getByRole('tab', { name: 'Minor' }).click();
  await page.getByRole('button', { name: 'Add new' }).nth(1).click();
  await page.getByRole('tab', { name: 'My Forms' }).click();
  await page.getByLabel('Select forms').click();
  await page.getByRole('option', { name: 'Automation Forms' }).first().click();
  await page.getByRole('combobox', { name: 'Select forms' }).click();
  await page.getByRole('button', { name: 'Add' }).nth(1).click();
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/verify?redirect_url=/forms/intake-package?active=Minor');
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/forms/intake-package?active=Minor');
  await page.getByRole('tab', { name: 'Couple' }).click();
  await page.getByRole('button', { name: 'Add new' }).nth(1).click();
  await page.getByRole('tab', { name: 'My Forms' }).click();
  await page.getByLabel('Select forms').click();
  await page.getByRole('option', { name: 'Automation Forms' }).first().click();
  await page.getByRole('combobox', { name: 'Select forms' }).click();
  await page.getByRole('button', { name: 'Add' }).nth(1).click();
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/forms/intake-package?active=Couple');
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/verify?redirect_url=/forms/intake-package?active=Couple');
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/forms/intake-package?active=Couple');
  await page.getByTestId('ArrowBackRoundedIcon').click();
//   Create Lead file
  await page.locator('div').filter({ hasText: /^Referrals$/ }).getByRole('img').click();
  await page.getByRole('button', { name: 'Create Lead' }).nth(1).click();
  await page.getByLabel('First Name*').click();
  await page.getByLabel('First Name*').fill('bangaloe');
  await page.getByLabel('Last Name').click();
  await page.getByLabel('Last Name').fill('23');
  await page.getByLabel('Phone').click();
  await page.getByLabel('Phone').fill('(939) 276-46294');
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('bank@gmail.com');
  await page.getByLabel('Seeking treatment for').click();
  await page.getByRole('option', { name: 'Cancer' }).click();
  await page.getByLabel('Note').click();
  await page.getByLabel('Note').fill('I am Very sick');
  await page.getByRole('button', { name: 'Create' }).nth(1).click();
  await page.getByRole('cell', { name: 'bangaloe' }).click();
  await page.getByRole('tab', { name: 'Basic Information' }).click();
  await page.getByLabel('Sex').click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByPlaceholder('MM/DD/YYYY').click();
  await page.getByPlaceholder('MM/DD/YYYY').fill('09/30/9');
  await page.getByLabel('Member ID').click();
  await page.getByLabel('Member ID').press('CapsLock');
  await page.getByLabel('Member ID').fill('GAH23');
  await page.getByLabel('Name on Card').click();
  await page.getByLabel('Name on Card').fill('RAJESHA');
  await page.getByLabel('Payer ID').click();
  await page.getByLabel('Payer ID').fill('BDJSB546');
  await page.getByLabel('Insurance Company').click();
  await page.getByRole('combobox', { name: 'Insurance Company' }).press('CapsLock');
  await page.getByRole('combobox', { name: 'Insurance Company' }).fill('abso');
  await page.getByText('ABSOLUTE TOTAL CARE-').click();
  await page.getByRole('button', { name: 'Save' }).nth(1).click();
  await page.getByLabel('Insurance Company').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('combobox', { name: 'Insurance Company' }).click();
  await page.getByRole('button', { name: 'Save' }).nth(1).click();
  await page.getByLabel('Insurance Company').click();
  await page.getByRole('combobox', { name: 'Insurance Company' }).fill('abs');
  await page.getByText('ABSOLUTE TOTAL CARE-').click();
  await page.getByRole('button', { name: 'Save' }).nth(1).click();
  await page.getByRole('tab', { name: 'Insurance' }).click();
  await page.getByRole('button', { name: 'Verify Benefits' }).nth(1).click();
  await page.getByRole('tab', { name: 'Attachments' }).click();
  await page.locator('span').filter({ hasText: 'Current Status :Inquiry' }).locator('div').nth(2).click();
  await page.getByRole('option', { name: 'Initial consultation call' }).click();
  await page.locator('div').filter({ hasText: /^Assign to$/ }).nth(1).click();
  await page.getByLabel('Choose team member').click();
  await page.getByRole('option', { name: 'Owner Team' }).click();
  await page.getByRole('button', { name: 'Cancel' }).nth(1).click();
  await page.getByLabel('Send inquiry form').click();
  await page.getByRole('button', { name: 'Send' }).nth(1).click();
  await page.getByLabel('Send inquiry form').click();
  await page.getByLabel('SMS').check();
  await page.getByRole('button', { name: 'Send' }).nth(1).click();
  await page.getByLabel('Send therapist scheduling link').click();
  await page.getByLabel('Select Therapist').click();
  await page.getByRole('option', { name: 'Owner Team' }).click();
  await page.getByRole('button', { name: 'Send' }).nth(1).click();
  await page.getByLabel('Add as client').click();
  await page.getByRole('button', { name: 'Continue' }).nth(1).click();
  await page.getByTestId('HighlightOffIcon').click();
  await page.locator('div').filter({ hasText: /^Filters \(01\)$/ }).getByRole('button').nth(2).click();
  await page.getByRole('row', { name: 'bangaloe 23 02/21/2024' }).getByLabel('Add as client').click();
  await page.getByRole('button', { name: 'Continue' }).nth(1).click();
  await page.locator('.MuiDialog-container').click();
  await page.getByTestId('HighlightOffIcon').locator('path').click();
// Calender Default is removing
  await page.locator('div').filter({ hasText: /^Calendar$/ }).getByRole('img').click();
  await page.getByRole('button', { name: 'Month' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('div').filter({ hasText: /^24$/ }).click();

});
