import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://enterprise-e8038.firebaseapp.com/__/auth/action?apiKey=AIzaSyD9w7OjQ1mbRxWX-kqUelVtwpnrxAhkpaA&mode=signIn&oobCode=H1iIQGu7qfPEv6h_gUXP-A-jcy2_qV-5G-tpK2jhiEkAAAGNofsriA&continueUrl=https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/auth/passwordless?email%3Dnewtestingntake@gmail.com&lang=en');
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/auth/passwordless?email=newtestingntake@gmail.com&apiKey=AIzaSyD9w7OjQ1mbRxWX-kqUelVtwpnrxAhkpaA&oobCode=H1iIQGu7qfPEv6h_gUXP-A-jcy2_qV-5G-tpK2jhiEkAAAGNofsriA&mode=signIn&lang=en');
  await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/appointments');
  await page.locator('div').filter({ hasText: /^Clients$/ }).getByRole('img').click();
//  Single clients ( Share Profile )
  await page.getByText('Anajali Kumari').click();
  await page.getByRole('button', { name: 'Profile & Clinician' }).nth(1).click();
  await page.getByRole('button', { name: 'Add profile' }).nth(1).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Therapist 4' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Anajali1');
  await page.getByRole('button', { name: 'Create' }).nth(1).click();

  await page.getByRole('button', { name: 'Add profile' }).nth(1).click();
  await page.getByLabel('Couple').check();
  await page.getByLabel('', { exact: true }).first().click();
  await page.getByRole('option', { name: 'Therapist 4' }).click();
  await page.getByRole('button', { name: '​', exact: true }).click();
  await page.getByRole('option', { name: 'Therapist client' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('button', { name: 'Cancel' }).nth(1).click();
  await page.getByRole('button').nth(2).click();
  
  await page.getByTestId('ArrowDropDownIcon').locator('path').click();
  await page.getByText('Anajali1Individual').click();
  await page.getByRole('tab', { name: 'Forms' }).click();
  await page.getByRole('tab', { name: 'Notes' }).click();
  await page.getByTestId('ArrowDropDownIcon').click();
  await page.getByRole('heading', { name: 'Anajali (OT)' }).click();
  await page.getByRole('tab', { name: 'Forms' }).click();
  await page.getByRole('button', { name: 'Send forms' }).nth(1).click();
  await page.getByRole('tab', { name: 'Personal' }).click();
  await page.getByText('Questionnaires').click();
  await page.getByLabel('Select Forms to send').click();
  await page.getByRole('combobox', { name: 'Select Forms to send' }).fill('Automation');
  await page.getByRole('option', { name: 'Automation Forms' }).click();
  await page.getByRole('combobox', { name: 'Select Forms to send' }).click();
  await page.getByRole('button', { name: 'Send' }).nth(1).click();
  await page.getByRole('tab', { name: 'Notes' }).click();
  await page.getByRole('button', { name: 'Add note' }).nth(1).click();
  await page.getByRole('button', { name: 'Add psychotherapy note' }).nth(1).click();
  await page.getByPlaceholder('Enter your response here').click();
  await page.getByPlaceholder('Enter your response here').fill('New Client list');
  await page.getByRole('button', { name: 'Save' }).nth(1).click();
  await page.getByRole('button', { name: 'Info & settings' }).nth(1).click();
  await page.getByLabel('Pronouns').click();
  await page.getByText('He/Him').click();
  await page.getByPlaceholder('MM/DD/YYYY').click();
  await page.getByPlaceholder('MM/DD/YYYY').fill('10/01/9');
  await page.getByLabel('First Name', { exact: true }).click();
  await page.getByLabel('First Name', { exact: true }).fill('Test');
  await page.getByLabel('Last Name', { exact: true }).click();
  await page.getByLabel('Last Name', { exact: true }).fill('1');
  await page.getByLabel('Email', { exact: true }).click();
  await page.getByLabel('Email', { exact: true }).fill('test1@gmail.com');
  await page.getByLabel('Phone', { exact: true }).click();
  await page.getByLabel('Phone', { exact: true }).fill('(839) 479-36426');
  await page.getByLabel('Relationship to client').click();
  await page.getByLabel('Relationship to client').fill('Brother');
  await page.getByLabel('Address Line').click();
  await page.getByLabel('Address Line').fill('New Man');
  await page.getByLabel('State').click();
  await page.getByRole('combobox', { name: 'State' }).fill('cali');
  await page.getByRole('option', { name: 'California' }).click();
  await page.getByLabel('City').click();
  await page.getByRole('combobox', { name: 'City' }).fill('Azua');
  await page.getByRole('button', { name: 'Save' }).nth(1).click();
  await page.getByRole('tab', { name: 'Files' }).click();
  await page.getByRole('button', { name: 'Request upload' }).nth(1).click();
  await page.getByLabel('Enter file name').click();
  await page.getByLabel('Enter file name').fill('test');
  await page.getByRole('button', { name: 'Add' }).nth(1).click();
  await page.getByLabel('Enter file name').nth(1).click();
  await page.getByLabel('Enter file name').nth(1).fill('1');
  await page.getByRole('button', { name: 'Request' }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Basic InfoIndividual$/ }).getByRole('button').click();
});