import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://u8165692.ct.sendgrid.net/ls/click?upn=u001.bGPC89E1b-2BR6sAgrMRX5pMCAFLd0GRFBAYQ-2Bw1BvVCRkjRzLfazgIk4E2lBlnyAxXk5-2BRHNgvVvGfhBFxf5VhakbAxrCoxcVKgy6Z3QoRWtMTzXYn1YKaWR0BoTpK-2FrYF8cFmi5zIXcO2snbtxLLT4FO7BT2mjtxhoZOTsvNrzIBAySgcHVhPHlRwHvBovFRi-2BgPsFYftpFPgVB-2B-2BYgJ6NKaqumbZM5rKVDrQgXqdMA2lQRcQ-2FuTJTscwbhL-2FnN8-2BHKQOFAJsWE-2BeTh-2FtPh6X0kaerlhZEM-2BwhZZuarBJf1CQEW5QW9a8xIgpXdeF1LSjd9S59Cip2EdJCkNoDNFJPiqEVs-2FdFDQBFTjwGu5ARbX9cXRN48SzVCSrE38sVBplqUWCaj3Ldg-2Flfmiqb9gCw-3D-3DBkaz_5y7MbatOEP89q1Cu8HxvHH-2FENdMmSYcAHJhv0ySewXh5874h2NArKLn-2FYJStU6VcY5kQY9k18BA5jnjdNaAVxvWmeHkcTHoO5LHpgZ8cG7pA6q9FGdohBdd0JFs63OoftLjgU17beD-2B2A7PGtN6vb4zF8ZgnOIZ9H0KlmdIi2Htek64iQpIoX9o2QBoaTbvhMlvAS8n26xVp5lQ7xes3HjHLSWBH0sth7bdqDPr-2F6Z20XOE9sME6lRo2gWjemkDhCp8OKwvbr3-2BdWFcZp5XrFKdorqik6eMSLpEVxtrWjZLLK46s202qaDgm9kyhbvCIQYb9r-2FqWqP0JSUYLzW95ygT-2F2msRYbsaypiN-2FNL8NKY-3D');
  
  await page.locator('div').filter({ hasText: /^Clients$/ }).getByRole('img').click();
  await page.getByText('Agent 1').click();
// await page.locator('div').filter({ hasText: /^Calendar$/ }).getByRole('img').click();
// await page.getByRole('button', { name: 'Month' }).click();
// await page.locator('div:nth-child(2) > div:nth-child(5) > .rbc-event > .rbc-addons-dnd-resizable > .rbc-event-content > ._eventContainer_1t36c_27 > .primary-ov-bold').click();
// await page.getByRole('tab', { name: 'Notes' }).click();
await page.getByRole('button', { name: 'Add', exact: true }).nth(1).click();
await page.getByRole('menuitem', { name: 'Appointment' }).click();
await page.getByRole('button', { name: 'Create Appointment' }).nth(1).click();
await page.getByText('Upcoming').click();
await page.getByRole('button', { name: 'Add note' }).nth(1).click();
await page.getByRole('tab', { name: 'Personal' }).click();
await page.getByText('Progress notes').click();
await page.getByPlaceholder('Search').click();
await page.getByPlaceholder('Search').fill('Therapist');
await page.getByRole('dialog').locator('div').filter({ hasText: /^Therapist Automation Testing$/ }).click();
await page.getByPlaceholder('Enter your response here').first().click();
await page.getByPlaceholder('Enter your response here').first().fill('Rajesh');
await page.getByPlaceholder('Enter your response here').nth(1).click();
await page.getByPlaceholder('Enter your response here').nth(1).fill('Good');
await page.getByPlaceholder('MM/DD/YYYY').click();
await page.getByPlaceholder('MM/DD/YYYY').fill('10/09/1999');
await page.getByRole('checkbox', { name: 'option1' }).check();
await page.locator('div').filter({ hasText: /^6Client CPT code\? \*Enter your response hereEnter your response here$/ }).getByLabel('Enter your response here').click();
await page.locator('div').filter({ hasText: /^6Client CPT code\? \*Enter your response hereEnter your response here$/ }).getByLabel('Enter your response here').fill('90791');
await page.getByRole('option', { name: '90791 - Psychiatric' }).click();
await page.locator('div').filter({ hasText: /^90791 - Psychiatric diagnostic evaluationEnter your response here$/ }).getByLabel('Enter your response here').click();
await page.locator('div').filter({ hasText: /^Enter your response here$/ }).getByLabel('Enter your response here').click();
await page.locator('div').filter({ hasText: /^Enter your response here$/ }).getByLabel('Enter your response here').fill('F05');
await page.getByRole('option', { name: 'F05 - Delirium due to known' }).click();
await page.locator('div').filter({ hasText: /^F05 - Delirium due to known physiological conditionEnter your response here$/ }).getByLabel('Enter your response here').click();
await page.locator('div').filter({ hasText: /^Sign here$/ }).nth(2).click();
await page.getByPlaceholder('Please type your name here').click();
await page.getByPlaceholder('Please type your name here').fill('Rajesh');
await page.getByRole('button', { name: 'Sign' }).nth(1).click();
await page.getByRole('button', { name: 'Save' }).nth(1).click();
await page.waitForTimeout(1000);
await page.getByText('Upcoming').click();
await page.waitForTimeout(2000);
await page.getByText('Therapist Automation Testing').click();
await page.getByRole('button', { name: 'Sign & Lock' }).nth(1).click();
await page.getByPlaceholder('Sign').click();
await page.getByPlaceholder('Sign').fill('Therapist 1');
await page.getByRole('button', { name: 'Sign and Lock' }).nth(1).click();
await page.locator('div').filter({ hasText: /^Therapist Automation Testing$/ }).getByRole('button').click();
await page.locator('div').filter({ hasText: /^Supervision$/ }).getByRole('img').click();
await page.getByText('Therapist Automation Testing').nth(1).click();
await page.locator('div').filter({ hasText: /^Therapist Automation Testing$/ }).getByRole('button').click();

// await page.getByRole('button', { name: 'Month' }).click();
// await page.locator('div:nth-child(2) > div:nth-child(5) > .rbc-event > .rbc-addons-dnd-resizable > .rbc-event-content > ._eventContainer_1t36c_27 > .primary-ov-bold').click();
// await page.locator('div').filter({ hasText: /^Therapist Automation Testing$/ }).click();
//   await page.getByRole('button', { name: 'Link appointment' }).nth(1).click();
//   await page.locator('._info_1fh2r_50 > .MuiButtonBase-root > .PrivateSwitchBase-input').first().check();
//   await page.getByRole('button', { name: 'Add' }).nth(1).click();
//   await page.getByRole('button', { name: 'Save' }).nth(1).click();
//   await page.goto('https://leafs-ehr-web-stage-nmvorvf7ga-as.a.run.app/clients/65e0035fb77e0f939df971ff?tab=Notes&clientProfileId=65e0035fb77e0f939df97201');
//   await page.locator('div').filter({ hasText: /^Supervision$/ }).getByRole('img').click();
//   await page.getByText('Therapist Automation TestingMar').click();
//   await page.getByRole('button', { name: 'Sign & Lock' }).nth(1).click();
//   await page.getByPlaceholder('Sign').click();
//   await page.getByPlaceholder('Sign').fill('Therapist 1');
//   await page.getByRole('button', { name: 'Sign and Lock' }).nth(1).click();
//   await page.locator('div').filter({ hasText: /^Therapist Automation Testing$/ }).getByRole('button').click();
});